version: 2.1
 
orbs:
  android: circleci/android@2.1.2

jobs:
  build:
    machine:
      image: android:2023.08.1
    steps:
      - checkout
      - java/setup:
          version: '17'
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Check Java version
          command: java -version
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file